(function(){var DEPS_GRAPH={'dcmenablermodule':[],'$weak$':['dcmenablermodule']};window.STUDIO_SDK_START=+new Date();var e,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},m=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ba="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={ga:!0},fa={};try{fa.__proto__=ea;da=fa.ga;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ha=ca,n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},r="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ia=function(a,b){if(b){var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}},ja=function(){ja=function(){};r.Symbol||(r.Symbol=
ka)},la=function(a,b){this.a=a;n(this,"description",{configurable:!0,writable:!0,value:b})};la.prototype.toString=function(){return this.a};
var ka=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new la("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}(),na=function(){ja();var a=r.Symbol.iterator;a||(a=r.Symbol.iterator=r.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&n(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}});na=function(){}},ma=function(a){na();a={next:a};a[r.Symbol.iterator]=function(){return this};return a},
t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ia("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!t(k,g)){var l=new b;n(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(p){if(p instanceof b)return p;d(p);return l(p)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),p=new a([[k,2],[l,3]]);if(2!=p.get(k)||3!=p.get(l))return!1;p["delete"](k);p.set(l,4);return!p.has(k)&&4==p.get(l)}catch(F){return!1}}())return a;
var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var q=0,h=function(k){this.a=(q+=Math.random()+1).toString();if(k){k=m(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};h.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!t(k,g))throw Error("WeakMap key fail: "+k);k[g][this.a]=l;return this};h.prototype.get=function(k){return c(k)&&t(k,g)?k[g][this.a]:void 0};h.prototype.has=function(k){return c(k)&&t(k,g)&&t(k[g],this.a)};
h.prototype["delete"]=function(k){return c(k)&&t(k,g)&&t(k[g],this.a)?delete k[g][this.a]:!1};return h});
ia("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(m([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),p=l.next();if(p.done||p.value[0]!=h||"s"!=p.value[1])return!1;p=l.next();return p.done||4!=p.value[0].x||"t"!=p.value[1]||!l.next().done?!1:!0}catch(F){return!1}}())return a;na();var b=new WeakMap,c=function(h){this.b={};this.a=
g();this.size=0;if(h){h=m(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.b[l.id]=[]);l.f?l.f.value=k:(l.f={next:this.a,h:this.a.h,head:this.a,key:h,value:k},l.list.push(l.f),this.a.h.next=l.f,this.a.h=l.f,this.size++);return this};c.prototype["delete"]=function(h){h=d(this,h);return h.f&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.b[h.id],h.f.h.next=h.f.next,h.f.next.h=h.f.h,h.f.head=null,
this.size--,!0):!1};c.prototype.clear=function(){this.b={};this.a=this.a.h=g();this.size=0};c.prototype.has=function(h){return!!d(this,h).f};c.prototype.get=function(h){return(h=d(this,h).f)&&h.value};c.prototype.entries=function(){return f(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return f(this,function(h){return h.key})};c.prototype.values=function(){return f(this,function(h){return h.value})};c.prototype.forEach=function(h,k){for(var l=this.entries(),p;!(p=l.next()).done;)p=
p.value,h.call(k,p[1],p[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++q,b.set(k,l)):l="p_"+k;var p=h.b[l];if(p&&t(h.b,l))for(h=0;h<p.length;h++){var F=p[h];if(k!==k&&F.key!==F.key||k===F.key)return{id:l,list:p,index:h,f:F}}return{id:l,list:p,index:-1,f:void 0}},f=function(h,k){var l=h.a;return ma(function(){if(l){for(;l.head!=h.a;)l=l.h;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};
l=null}return{done:!0,value:void 0}})},g=function(){var h={};return h.h=h.next=h.head=h},q=0;return c});
var u=this||self,v=function(a,b,c){a=a.split(".");c=c||u;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},oa=function(){},w=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&
"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},x=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},y=function(a,b){function c(){}c.prototype=b.prototype;a.fa=b.prototype;
a.prototype=new c;a.prototype.constructor=a};var pa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},qa=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},ra=function(a){return Array.prototype.concat.apply([],arguments)},
sa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ta=function(a){this.a=a};v("studio.common.mde.Direction",ta,void 0);ta.Corner={ma:0,na:1,ia:2,ja:3};ta.prototype.toString=function(){return(this.a&2?"b":"t")+(this.a&1?"r":"l")};var z=function(){};v("studio.common.Environment",z,void 0);z.Type={LIVE:1,LOCAL:2,BROWSER:4,IN_APP:8,LAYOUTS_PREVIEW:16,CREATIVE_TOOLSET:32,RENDERING_STUDIO:64,RENDERING_TEST:128,PREVIEW:256};var A=6;z.addType=function(a){A|=a;ua(a)};var va=function(a){A=a|6;ua(A)};z.setType=va;z.hasType=function(a){return(A&a)==a};z.getValue=function(){return A};var ua=function(a){B(a,2,1);B(a,1,2);B(a,4,8);B(a,8,4);B(a,128,64);B(a,64,128);B(a,256,2)},B=function(a,b,c){(a&b)==b&&(A|=b,A&=~c)};var wa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},xa=function(a,b){return a<b?-1:a>b?1:0};var C;a:{var ya=u.navigator;if(ya){var za=ya.userAgent;if(za){C=za;break a}}C=""};var Aa=function(a){Aa[" "](a);return a};Aa[" "]=oa;var Ba=-1!=C.indexOf("Opera"),D=-1!=C.indexOf("Trident")||-1!=C.indexOf("MSIE"),Ca=-1!=C.indexOf("Edge"),Da=-1!=C.indexOf("Gecko")&&!(-1!=C.toLowerCase().indexOf("webkit")&&-1==C.indexOf("Edge"))&&!(-1!=C.indexOf("Trident")||-1!=C.indexOf("MSIE"))&&-1==C.indexOf("Edge"),Ea=-1!=C.toLowerCase().indexOf("webkit")&&-1==C.indexOf("Edge"),Fa=function(){var a=u.document;return a?a.documentMode:void 0},Ga;
a:{var Ha="",Ia=function(){var a=C;if(Da)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ca)return/Edge\/([\d\.]+)/.exec(a);if(D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ea)return/WebKit\/(\S+)/.exec(a);if(Ba)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ia&&(Ha=Ia?Ia[1]:"");if(D){var Ja=Fa();if(null!=Ja&&Ja>parseFloat(Ha)){Ga=String(Ja);break a}}Ga=Ha}var Ka=Ga,La={},Ma;Ma=u.document&&D?Fa():void 0;var E=function(a,b){this.width=a;this.height=b};E.prototype.aspectRatio=function(){return this.width/this.height};E.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};E.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};E.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Na={ka:"dcm",la:"studio"};v("studio.sdk.ContainerState",{COLLAPSING:"collapsing",COLLAPSED:"collapsed",EXPANDING:"expanding",EXPANDED:"expanded",FS_COLLAPSING:"fs_collapsing",FS_EXPANDING:"fs_expanding",FS_EXPANDED:"fs_expanded"},void 0);var Oa=function(){};var Pa;(Pa=!D)||(Pa=9<=Number(Ma));var Qa=Pa,Ra;
if(Ra=D){var Sa;if(Object.prototype.hasOwnProperty.call(La,"9"))Sa=La["9"];else{for(var Ta=0,Ua=wa(String(Ka)).split("."),Va=wa("9").split("."),Wa=Math.max(Ua.length,Va.length),Xa=0;0==Ta&&Xa<Wa;Xa++){var Ya=Ua[Xa]||"",Za=Va[Xa]||"";do{var G=/(\d*)(\D*)(.*)/.exec(Ya)||["","","",""],H=/(\d*)(\D*)(.*)/.exec(Za)||["","","",""];if(0==G[0].length&&0==H[0].length)break;Ta=xa(0==G[1].length?0:parseInt(G[1],10),0==H[1].length?0:parseInt(H[1],10))||xa(0==G[2].length,0==H[2].length)||xa(G[2],H[2]);Ya=G[3];
Za=H[3]}while(0==Ta)}Sa=La["9"]=0<=Ta}Ra=!Sa}var $a=Ra,ab=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",oa,b),u.removeEventListener("test",oa,b)}catch(c){}return a}();var I=function(a,b){this.type=a;this.a=this.target=b};I.prototype.c=function(){};var J=function(a,b){I.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.b=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;if(b=a.relatedTarget){if(Da){a:{try{Aa(b.nodeName);var f=!0;break a}catch(g){}f=!1}f||(b=
null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:bb[a.pointerType]||"";this.b=a;a.defaultPrevented&&this.c()}};y(J,I);var bb={2:"touch",3:"pen",4:"mouse"};J.prototype.c=function(){J.fa.c.call(this);var a=this.b;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,$a)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var K="closure_listenable_"+(1E6*Math.random()|0),cb=0;var db=function(a,b,c,d,f){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=f;this.key=++cb;this.m=this.v=!1},eb=function(a){a.m=!0;a.listener=null;a.a=null;a.src=null;a.b=null};var fb=function(a){this.src=a;this.a={};this.b=0};fb.prototype.add=function(a,b,c,d,f){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var q=gb(a,b,d,f);-1<q?(b=a[q],c||(b.v=!1)):(b=new db(b,this.src,g,!!d,f),b.v=c,a.push(b));return b};
var hb=function(a,b){var c=b.type;if(c in a.a){var d=a.a[c],f=pa(d,b),g;(g=0<=f)&&Array.prototype.splice.call(d,f,1);g&&(eb(b),0==a.a[c].length&&(delete a.a[c],a.b--))}},gb=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.m&&g.listener==b&&g.capture==!!c&&g.b==d)return f}return-1};var ib="closure_lm_"+(1E6*Math.random()|0),jb={},kb=0,L=function(a,b,c,d,f){if(d&&d.once)return lb(a,b,c,d,f);if("array"==w(b)){for(var g=0;g<b.length;g++)L(a,b[g],c,d,f);return null}c=mb(c);return a&&a[K]?a.a.add(String(b),c,!1,x(d)?!!d.capture:!!d,f):nb(a,b,c,!1,d,f)},nb=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var q=x(f)?!!f.capture:!!f,h=ob(a);h||(a[ib]=h=new fb(a));c=h.add(b,c,d,q,g);if(c.a)return c;d=pb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)ab||(f=q),void 0===
f&&(f=!1),a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(qb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");kb++;return c},pb=function(){var a=rb,b=Qa?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},lb=function(a,b,c,d,f){if("array"==w(b)){for(var g=0;g<b.length;g++)lb(a,b[g],c,d,f);return null}c=mb(c);return a&&
a[K]?a.a.add(String(b),c,!0,x(d)?!!d.capture:!!d,f):nb(a,b,c,!0,d,f)},sb=function(a,b,c,d,f){if("array"==w(b))for(var g=0;g<b.length;g++)sb(a,b[g],c,d,f);else(d=x(d)?!!d.capture:!!d,c=mb(c),a&&a[K])?(a=a.a,b=String(b).toString(),b in a.a&&(g=a.a[b],c=gb(g,c,d,f),-1<c&&(eb(g[c]),Array.prototype.splice.call(g,c,1),0==g.length&&(delete a.a[b],a.b--)))):a&&(a=ob(a))&&(b=a.a[b.toString()],a=-1,b&&(a=gb(b,c,d,f)),(c=-1<a?b[a]:null)&&tb(c))},tb=function(a){if("number"!==typeof a&&a&&!a.m){var b=a.src;if(b&&
b[K])hb(b.a,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(qb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);kb--;(c=ob(b))?(hb(c,a),0==c.b&&(c.src=null,b[ib]=null)):eb(a)}}},qb=function(a){return a in jb?jb[a]:jb[a]="on"+a},vb=function(a,b,c,d){var f=!0;if(a=ob(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.m&&(g=ub(g,d),f=f&&!1!==g)}return f},ub=function(a,b){var c=a.listener,
d=a.b||a.src;a.v&&tb(a);return c.call(d,b)},rb=function(a,b){if(a.m)return!0;if(!Qa){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new J(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var f=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(q){f=!0}if(f||void 0==d.returnValue)d.returnValue=!0}d=[];for(f=b.a;f;f=f.parentNode)d.push(f);a=a.type;for(f=d.length-1;0<=f;f--){b.a=d[f];var g=vb(d[f],a,!0,b);c=c&&g}for(f=0;f<d.length;f++)b.a=
d[f],g=vb(d[f],a,!1,b),c=c&&g}return c}return ub(a,new J(b,this))},ob=function(a){a=a[ib];return a instanceof fb?a:null},wb="__closure_events_fn_"+(1E9*Math.random()>>>0),mb=function(a){if("function"==w(a))return a;a[wb]||(a[wb]=function(b){return a.handleEvent(b)});return a[wb]};var M=function(a){this.i=a;this.g={}};y(M,Oa);var xb=[],yb=function(a,b,c){var d=document.body||window,f={capture:!0,passive:!0};"array"!=w(b)&&(b&&(xb[0]=b.toString()),b=xb);for(var g=0;g<b.length;g++){var q=L(d,b[g],c||a.handleEvent,f||!1,a.i||a);if(!q)break;a.g[q.key]=q}};M.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var N=function(){M.call(this);this.a=new Map;this.b=!1;this.a.set("nx",null);this.a.set("ny",null);this.a.set("dim",null)};N.prototype=ba(M.prototype);N.prototype.constructor=N;if(ha)ha(N,M);else for(var O in M)if("prototype"!=O)if(Object.defineProperties){var zb=Object.getOwnPropertyDescriptor(M,O);zb&&Object.defineProperty(N,O,zb)}else N[O]=M[O];N.fa=M.prototype;
N.prototype.c=function(a){var b=a.clientX,c=a.clientY;a.changedTouches&&a.changedTouches[0]&&(b=a.changedTouches[0].clientX,c=a.changedTouches[0].clientY);this.a.set("nx",Math.round(b));this.a.set("ny",Math.round(c))};v("studio.sdk.MraidMethod",{GET_CURRENT_POSITION:"getCurrentPosition",GET_DEFAULT_POSITION:"getDefaultPosition",GET_SCREEN_SIZE:"getScreenSize",CREATE_CALENDAR_EVENT:"createCalendarEvent",GET_MAX_SIZE:"getMaxSize",PLAY_VIDEO:"playVideo",STORE_PICTURE:"storePicture",SUPPORTS:"supports",USE_CUSTOM_CLOSE:"useCustomClose"},void 0);var Ab=function(){};v("studio.sdk.IEnabler",Ab,void 0);e=Ab.prototype;e.aa=function(){};e.W=function(){};e.V=function(){};e.ca=function(){};e.ba=function(){};e.isVisible=function(){};e.R=function(){};e.P=function(){};e.O=function(){};e.A=function(){};e.getParameter=function(){};e.w=function(){};e.C=function(){};e.I=function(){};e.B=function(){};e.da=function(){};e.ea=function(){};e.J=function(){};e.K=function(){};e.Y=function(){};e.F=function(){};e.X=function(){};e.D=function(){};e.close=function(){};
e.M=function(){};e.S=function(){};e.addEventListener=function(){};e.removeEventListener=function(){};e.U=function(){};e.T=function(){};e.$=function(){};e.H=function(){};e.Z=function(){};e.G=function(){};e.L=function(){};e.N=function(){};v("studio.sdk.logger",{}.oa,void 0);v("studio.module.ModuleId",{ENABLER:"enabler",DCM_ENABLER:"dcmenabler",VIDEO:"video",CONFIGURABLE:"configurable",CONFIGURABLE_FILLER:"configurablefiller",LAYOUTS:"layouts",FILLER:"layoutsfiller",RAD_VIDEO:"rad_ui_video",GDN:"gdn"},void 0);/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var P=function(a,b){this.b={};this.a=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof P)for(c=a.j(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};P.prototype.l=function(){Bb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};P.prototype.j=function(){Bb(this);return this.a.concat()};
var Bb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Q(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var f={};for(c=b=0;b<a.a.length;)d=a.a[b],Q(f,d)||(a.a[c++]=d,f[d]=1),b++;a.a.length=c}};P.prototype.get=function(a,b){return Q(this.b,a)?this.b[a]:b};P.prototype.set=function(a,b){Q(this.b,a)||(this.c++,this.a.push(a));this.b[a]=b};P.prototype.forEach=function(a,b){for(var c=this.j(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};
var Q=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var R=function(){this.a=new fb(this)};y(R,Oa);R.prototype[K]=!0;R.prototype.addEventListener=function(a,b,c,d){L(this,a,b,c,d)};R.prototype.removeEventListener=function(a,b,c,d){sb(this,a,b,c,d)};var S=new P;S.set("enabler","enabler");S.set("dcmenabler","dcm");S.set("video","vid");S.set("configurable","cfg");S.set("configurablefiller","cfg_fill");S.set("layouts","lay");S.set("layoutsfiller","lay_fill");S.set("gdn","gdn");S.set("rad_ui_video","rad");v("goog.exportSymbol",function(a,b,c){v(a,b,c)},this);var Cb=function(a){a+="goog.exportSymbol('studioLoader.context.evalInContext', "+Cb.toString()+");";eval(a)};v("studioLoader.context.evalInContext",Cb,void 0);var Db=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Eb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var Fb=function(){var a=(window.STUDIO_ORIGINAL_ASSET_URL?window.STUDIO_ORIGINAL_ASSET_URL:window.location.href).replace(/%(?![A-Fa-f0-9][A-Fa-f0-9])/g,"%25");this.g=this.u=this.c="";this.s=null;this.i=this.o="";this.a=!1;if(a instanceof Fb){this.a=a.a;Gb(this,a.c);this.u=a.u;this.g=a.g;Hb(this,a.s);this.o=a.o;var b=a.b;var c=new T;c.c=b.c;b.a&&(c.a=new P(b.a),c.b=b.b);Ib(this,c);this.i=a.i}else a&&(b=String(a).match(Db))?(this.a=!1,Gb(this,b[1]||"",!0),this.u=U(b[2]||""),this.g=U(b[3]||"",!0),Hb(this,
b[4]),this.o=U(b[5]||"",!0),Ib(this,b[6]||"",!0),this.i=U(b[7]||"")):(this.a=!1,this.b=new T(null,this.a))};
Fb.prototype.toString=function(){var a=[],b=this.c;b&&a.push(V(b,Jb,!0),":");var c=this.g;if(c||"file"==b)a.push("//"),(b=this.u)&&a.push(V(b,Jb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.o)this.g&&"/"!=c.charAt(0)&&a.push("/"),a.push(V(c,"/"==c.charAt(0)?Kb:Lb,!0));(c=this.b.toString())&&a.push("?",c);(c=this.i)&&a.push("#",V(c,Mb));return a.join("")};
var Gb=function(a,b,c){a.c=c?U(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},Hb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.s=b}else a.s=null},Ib=function(a,b,c){b instanceof T?(a.b=b,Nb(a.b,a.a)):(c||(b=V(b,Ob)),a.b=new T(b,a.a))},U=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},V=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Pb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Pb=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Jb=/[#\/\?@]/g,Lb=/[#\?:]/g,Kb=/[#\?]/g,Ob=/[#\?@]/g,Mb=/#/g,T=function(a,b){this.b=this.a=null;this.c=a||null;this.g=!!b},W=function(a){a.a||(a.a=new P,a.b=0,a.c&&Eb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};T.prototype.add=function(a,b){W(this);this.c=null;a=X(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
var Qb=function(a,b){W(a);b=X(a,b);Q(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,Q(a.b,b)&&(delete a.b[b],a.c--,a.a.length>2*a.c&&Bb(a)))},Rb=function(a,b){W(a);b=X(a,b);return Q(a.a.b,b)};e=T.prototype;e.forEach=function(a,b){W(this);this.a.forEach(function(c,d){qa(c,function(f){a.call(b,f,d,this)},this)},this)};e.j=function(){W(this);for(var a=this.a.l(),b=this.a.j(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};
e.l=function(a){W(this);var b=[];if("string"===typeof a)Rb(this,a)&&(b=ra(b,this.a.get(X(this,a))));else{a=this.a.l();for(var c=0;c<a.length;c++)b=ra(b,a[c])}return b};e.set=function(a,b){W(this);this.c=null;a=X(this,a);Rb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};e.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};
e.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.j(),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.l(d);for(var g=0;g<d.length;g++){var q=f;""!==d[g]&&(q+="="+encodeURIComponent(String(d[g])));a.push(q)}}return this.c=a.join("&")};
var X=function(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b},Nb=function(a,b){b&&!a.g&&(W(a),a.c=null,a.a.forEach(function(c,d){var f=d.toLowerCase();d!=f&&(Qb(this,d),Qb(this,f),0<c.length&&(this.c=null,this.a.set(X(this,f),sa(c)),this.b+=c.length))},a));a.g=b};var Y=function(a){L(window,"message",Sb);if(a!=Tb)return!1;R.call(this);this.b=null;this.b||(this.b=new Fb);(a=this.g=this.b.b)&&(a=a.get("e",null))&&va(parseInt(a,10)||0);a=this.c=new N;a.b=!0;yb(a,"mousedown",a.c);yb(a,"touchstart",a.c)},Ub;y(Y,R);v("studio.DcmEnabler",Y,void 0);var Tb=Math.random(),Vb=null,Wb={},Xb=function(){Vb||(Vb=new Y(Tb));return Vb};Y.getInstance=Xb;
var Sb=function(a){if("string"===typeof a.b.data){try{var b=JSON.parse(a.b.data)}catch(f){return}if(b.isInitClickTag){if(a=b.clickTags)for(var c=0;c<a.length;c++){var d=a[c];Wb[d.name]=d.url}Ub=b.relegateNavigation}}};Y.prototype.W=function(){};Y.prototype.reportManualClose=Y.prototype.W;Y.prototype.V=function(){};Y.prototype.reportEngagement=Y.prototype.V;Y.prototype.aa=function(){};Y.prototype.setExpandingPixelOffsets=Y.prototype.aa;Y.prototype.ca=function(){};Y.prototype.setStartExpanded=Y.prototype.ca;
Y.prototype.ba=function(){};Y.prototype.setIsMultiDirectional=Y.prototype.ba;Y.prototype.isVisible=function(){return!0};Y.prototype.isVisible=Y.prototype.isVisible;Y.prototype.R=function(){return!0};Y.prototype.isServingInLiveEnvironment=Y.prototype.R;Y.prototype.P=function(){return!0};Y.prototype.isPageLoaded=Y.prototype.P;Y.prototype.O=function(){return!0};Y.prototype.isInitialized=Y.prototype.O;Y.prototype.A=function(){};Y.prototype.callAfterInitialized=Y.prototype.A;
Y.prototype.getParameter=function(a){return this.g.get(a,null)};Y.prototype.getParameter=Y.prototype.getParameter;
Y.prototype.w=function(a,b){if(a=null!=Wb[a]&&"null"!=Wb[a]?Wb[a]:b){var c=this.c;if(c.b){b=window.document;b="CSS1Compat"==b.compatMode?b.documentElement:b.body;b=new E(b.clientWidth,b.clientHeight);c.a.set("dim",b.width+"x"+b.height);b="";c=m(c.a);for(var d=c.next();!d.done;d=c.next()){var f=m(d.value);d=f.next().value;f=f.next().value;b=null==f?b+"&"+d+"=":b+"&"+d+"="+f}c=a.toLowerCase().indexOf("&adurl=");-1<c&&34>=b.length&&(a=a.substr(0,c)+b+a.substr(c))}}"parent"===Ub?window.parent.postMessage(JSON.stringify({clickTag:a,
isPostClickTag:!0}),"*"):window.open(a)};Y.prototype.exit=Y.prototype.w;Y.prototype.C=function(a,b){this.w(a,b)};Y.prototype.exitOverride=Y.prototype.C;Y.prototype.I=function(a){return a};Y.prototype.formExitUrlFromOverride=Y.prototype.I;Y.prototype.B=function(){};Y.prototype.counter=Y.prototype.B;Y.prototype.da=function(){};Y.prototype.startTimer=Y.prototype.da;Y.prototype.ea=function(){};Y.prototype.stopTimer=Y.prototype.ea;Y.prototype.J=function(){return"collapsed"};
Y.prototype.getContainerState=Y.prototype.J;Y.prototype.K=function(){return null};Y.prototype.getExpandDirection=Y.prototype.K;Y.prototype.Y=function(){};Y.prototype.requestExpand=Y.prototype.Y;Y.prototype.F=function(){};Y.prototype.finishExpand=Y.prototype.F;Y.prototype.X=function(){};Y.prototype.requestCollapse=Y.prototype.X;Y.prototype.D=function(){};Y.prototype.finishCollapse=Y.prototype.D;Y.prototype.close=function(){};Y.prototype.close=Y.prototype.close;Y.prototype.M=function(a){return a};
Y.prototype.getUrl=Y.prototype.M;Y.prototype.S=function(){};Y.prototype.loadModule=Y.prototype.S;Y.prototype.addEventListener=function(a,b,c,d){L(this,a,b,c,d)};Y.prototype.addEventListener=Y.prototype.addEventListener;Y.prototype.removeEventListener=function(a,b,c,d){sb(this,a,b,c,d)};Y.prototype.removeEventListener=Y.prototype.removeEventListener;Y.prototype.U=function(){};Y.prototype.queryFullscreenSupport=Y.prototype.U;Y.prototype.T=function(){};Y.prototype.queryFullscreenDimensions=Y.prototype.T;
Y.prototype.$=function(){};Y.prototype.requestFullscreenExpand=Y.prototype.$;Y.prototype.H=function(){};Y.prototype.finishFullscreenExpand=Y.prototype.H;Y.prototype.Z=function(){};Y.prototype.requestFullscreenCollapse=Y.prototype.Z;Y.prototype.G=function(){};Y.prototype.finishFullscreenCollapse=Y.prototype.G;Y.prototype.N=function(){};Y.prototype.invokeMraidMethod=Y.prototype.N;Y.prototype.L=function(){a:{for(a in Na)if("dcm"==Na[a]){var a="dcm";break a}a=null}return a||"dcm"};
Y.prototype.getSdk=Y.prototype.L;var Yb=Xb();v("Enabler",Yb,void 0);var Z=function(a){I.call(this,a)};y(Z,I);v("studio.events.StudioEvent",Z,void 0);Z.INIT="init";Z.VISIBLE="visible";Z.HIDDEN="hidden";Z.VISIBILITY_CHANGE="visibilityChange";Z.VISIBILITY_CHANGE_WITH_INFO="visibilityChangeWithInfo";Z.EXIT="exit";Z.INTERACTION="interaction";Z.PAGE_LOADED="pageLoaded";Z.ORIENTATION="orientation";Z.ABOUT_TO_EXPAND="aboutToExpand";Z.EXPAND_START="expandStart";Z.EXPAND_FAILED="expandFailed";Z.EXPAND_FINISH="expandFinish";Z.COLLAPSE_START="collapseStart";
Z.COLLAPSE_FINISH="collapseFinish";Z.COLLAPSE="collapse";Z.FULLSCREEN_SUPPORT="fullscreenSupport";Z.HOSTPAGE_FEATURES_LOADED="hostpageFeaturesLoaded";Z.FULLSCREEN_DIMENSIONS="fullscreenDimensions";Z.FULLSCREEN_EXPAND_START="fullscreenExpandStart";Z.FULLSCREEN_EXPAND_FINISH="fullscreenExpandFinish";Z.FULLSCREEN_COLLAPSE_START="fullscreenCollapseStart";Z.FULLSCREEN_COLLAPSE_FINISH="fullscreenCollapseFinish";Z.HOSTPAGE_SCROLL="hostpageScroll";Z.OPTIONAL_HOSTPAGE_SCROLL="optHostpageScroll";
Z.SCROLL_INTERACTION="scrollInteraction";Z.ENTER_VIEWPORT="enterViewport";Z.OPTIONAL_ENTER_VIEWPORT="optEnterViewport";Z.EXIT_VIEWPORT="exitViewport";Z.OPTIONAL_EXIT_VIEWPORT="optExitViewport";Z.VIDEO_START="videoStart";Z.prototype.ha=function(a,b){this[a]=b;return this};Z.prototype.addProperty=Z.prototype.ha;})();
