version: "3.9"

services:
  websphere-liberty:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:9080"
      - "443:9443"

  ibm-mq:
    image: ibmcom/mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ENABLE_METRICS: true
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157"
