//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:16:27 PM YAKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geekbrains.com/geek/market/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.geekbrains.geek.market.soap;
