spring:
  application:
    name: statistic-chain-client

server:
  port: 9095

eureka:
  client:
    serviceUrl.defaultZone:${EUREKA_URI:http://localhost:8761/eureka}
    instance.preferIpAddress:true

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8880/auth/user
    client:
      client-id: flametoken
      client-secret: thisissecret