server:
  port: 8880

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=boot
    username: postgres
    password: 178ueee34
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
# eureka.client.registerWithEureka=false
# eureka.client.fetchRegistry=false

# spring.cloud.config.uri=http://localhost:8081

# spring.cloud.config.username=root
# spring.cloud.config.password=s3cr3t
# spring.cloud.config.name=conf
# spring.cloud.config.uri=http://localhost:8081